let words=JSON.parse(localStorage.getItem('vocab3600-words')||'null')||[];let open=new Set(),quizWord=null,reviewWord=null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const save=()=>localStorage.setItem('vocab3600-words',JSON.stringify(words));
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='dashboard')dash();if(id==='words')renderWords();if(id==='quiz')newQuiz();if(id==='review')review()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function dash(){let n=words.filter(w=>(w.status||'new')==='new').length,l=words.filter(w=>w.status==='learning').length,d=words.filter(w=>w.status==='learned').length;['sTotal','sNew','sLearning','sLearned'].forEach((x,i)=>$(x).textContent=[words.length,n,l,d][i]);$('progress').innerHTML=['A1','A2','B1','B2','C1','C2'].map(v=>{let a=words.filter(w=>w.level===v),d=a.filter(w=>w.status==='learned').length,p=a.length?Math.round(d/a.length*100):0;return `<div>${v} — ${p}%<div style="height:8px;background:var(--card2);border-radius:9px"><div style="height:100%;width:${p}%;background:var(--accent);border-radius:9px"></div></div></div>`}).join('<br>');$('reviewInfo').textContent=words.filter(w=>!w.nextReview||w.nextReview<=Date.now()).length+' words due for review.'}
function renderWords(){let q=($('search').value||'').toLowerCase(),s=$('status').value,l=$('level').value,sort=$('sort').value,a=words.filter(w=>(!q||JSON.stringify(w).toLowerCase().includes(q))&&(s==='all'||(s==='favorite'?w.favorite:w.status===s))&&(l==='all'||w.level===l));a.sort((x,y)=>sort==='za'?y.word.localeCompare(x.word):sort==='newest'?(y.created||0)-(x.created||0):x.word.localeCompare(y.word));$('wordCount').textContent=`Showing ${a.length} of ${words.length} words`;$('wordList').innerHTML=a.map(card).join('')||'<div class="panel">No words found.</div>'}
function card(w){let o=open.has(w.id);return `<article class="wordCard ${o?'open':''}"><div class="wordHead" onclick="toggle('${w.id}')"><span class="arrow">${o?'⌄':'›'}</span><span class="wordName">${esc(w.word)}</span><span class="meaning">${esc(w.meaning)}</span><span class="badge">${esc(w.level)}</span><button class="icon ${w.favorite?'fav':''}" onclick="event.stopPropagation();fav('${w.id}')">${w.favorite?'★':'☆'}</button></div><div class="details"><section><h4>Meaning / pronunciation</h4><b>${esc(w.meaning||'—')}</b> ${esc(w.ipa||'')} ${esc(w.pos||'')}</section><section><h4>Examples</h4><ul class="examples">${(w.examples||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>—</li>'}</ul></section>${['synonyms','antonyms','collocations','forms'].map(k=>w[k]?.length?`<section><h4>${k}</h4><div class="chips">${w[k].map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>`:'').join('')}${w.images?.length?`<section><h4>Images</h4><div class="media">${w.images.map(x=>`<img src="${esc(x)}" alt="${esc(w.word)}" loading="lazy">`).join('')}</div></section>`:''}${w.audio?`<section><h4>Audio</h4><audio controls src="${esc(w.audio)}"></audio></section>`:''}${w.video?`<section><h4>Video</h4><a target="_blank" href="${esc(w.video)}">▶ Open video</a></section>`:''}<div class="actions"><button onclick="editWord('${w.id}')">✏️ Edit</button><button onclick="cycle('${w.id}')">Status: ${esc(w.status||'new')}</button><button onclick="del('${w.id}')">🗑️ Delete</button></div></div></article>`}
function toggle(id){open.has(id)?open.delete(id):open.add(id);renderWords()}function fav(id){let w=words.find(x=>x.id===id);w.favorite=!w.favorite;save();renderWords()}function cycle(id){let w=words.find(x=>x.id===id),a=['new','learning','learned'];w.status=a[(a.indexOf(w.status||'new')+1)%3];save();renderWords();dash()}function del(id){let w=words.find(x=>x.id===id);if(confirm('Delete '+w.word+'?')){words=words.filter(x=>x.id!==id);save();renderWords();dash()}}
function openEditor(w){$('modal').classList.remove('hidden');$('modalTitle').textContent=w?'Edit Word':'Add Word';$('editId').value=w?.id||'';[['fWord','word'],['fMeaning','meaning'],['fLevel','level'],['fIpa','ipa'],['fPos','pos'],['fAudio','audio'],['fVideo','video']].forEach(([a,b])=>$(a).value=w?.[b]||'');$('fExamples').value=(w?.examples||[]).join('\n');$('fSyn').value=(w?.synonyms||[]).join(', ');$('fAnt').value=(w?.antonyms||[]).join(', ');$('fColl').value=(w?.collocations||[]).join(', ');$('fForms').value=(w?.forms||[]).join(', ');$('fImages').value=(w?.images||[]).join('\n')}
function closeEditor(){$('modal').classList.add('hidden')}function editWord(id){openEditor(words.find(w=>w.id===id))}
const lines=id=>$(id).value.split('\n').map(x=>x.trim()).filter(Boolean),csv=id=>$(id).value.split(',').map(x=>x.trim()).filter(Boolean);
$('wordForm').onsubmit=e=>{e.preventDefault();let id=$('editId').value,w=words.find(x=>x.id===id),d={word:$('fWord').value.trim(),meaning:$('fMeaning').value.trim(),level:$('fLevel').value,ipa:$('fIpa').value.trim(),pos:$('fPos').value.trim(),examples:lines('fExamples'),synonyms:csv('fSyn'),antonyms:csv('fAnt'),collocations:csv('fColl'),forms:csv('fForms'),audio:$('fAudio').value.trim(),video:$('fVideo').value.trim(),images:lines('fImages')};if(!d.word)return;if(w)Object.assign(w,d);else words.push({id:crypto.randomUUID(),...d,status:'new',favorite:false,created:Date.now(),nextReview:Date.now()});save();closeEditor();renderWords();dash()};
function newQuiz(){if(!words.length){$('quizBox').innerHTML='<p>Add words first.</p>';return}quizWord=words[Math.floor(Math.random()*words.length)];let p=[quizWord,...words.filter(w=>w.id!==quizWord.id).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);$('quizBox').innerHTML=`<p>What does this word mean?</p><div class="question">${esc(quizWord.word)}</div><div class="answers">${p.map(w=>`<button onclick="answer('${w.id}')">${esc(w.meaning||'No meaning')}</button>`).join('')}</div><div id="feedback"></div>`}function answer(id){document.querySelectorAll('.answers button').forEach(b=>b.disabled=true);$('feedback').innerHTML=id===quizWord.id?'✅ Correct!':'❌ Answer: '+esc(quizWord.meaning);if(id===quizWord.id){quizWord.status='learned';save()}}
function review(){let n=words.filter(w=>!w.nextReview||w.nextReview<=Date.now()).length;$('reviewBox').innerHTML=`<p>${n} words are due.</p><button class="primary" onclick="startReview()">Start review</button>`}function startReview(){let a=words.filter(w=>!w.nextReview||w.nextReview<=Date.now());reviewWord=a[Math.floor(Math.random()*a.length)];if(!reviewWord){review();return}$('reviewBox').innerHTML=`<p>How well do you know this word?</p><div class="question">${esc(reviewWord.word)}</div><div class="answers"><button onclick="rate(1)">😵 Again</button><button onclick="rate(2)">😐 Hard</button><button onclick="rate(3)">🙂 Good</button><button onclick="rate(4)">😎 Easy</button></div>`}function rate(n){let days=[0,1,3,7,14][n];reviewWord.nextReview=Date.now()+days*86400000;reviewWord.status=n>=3?'learned':'learning';save();startReview();dash()}
$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('vocab3600-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('vocab3600-theme')==='light')document.body.classList.add('light');
fetch('data/words.json').then(r=>r.json()).then(d=>{if(!localStorage.getItem('vocab3600-words')){words=d;save()}dash();showView('dashboard')}).catch(()=>{dash();showView('dashboard')});
